

on: [release]
name: Run gcloud command
jobs:
  GCPAuthenticate:
    name: GCP Authenticate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: GCP Authenticate
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
    - name: GCP List Clusters
      uses: actions/gcloud/cli@master
      with:
        args: functions deploy triangleData --runtime nodejs10 --trigger-http
